### ISSUE TITLE
23H2 failed, still need TPM2.0

### ISSUE THREAD

**Issue by kingyue737** [JosephM101/Force-Windows-11-Install#18]
![image](https://github.com/JosephM101/Force-Windows-11-Install/assets/40021217/29e2a613-a630-405c-90f9-2d6fae02095d)
`Win11-New.iso` is generated successfully.

But TPM still cannot be bypassed:

![image](https://github.com/JosephM101/Force-Windows-11-Install/assets/40021217/361d51f3-b268-446f-83c5-6ed2ecb21445)

**Comment by JosephM101** [comment]
It looks like what you're doing is mounting the modified ISO, and running `setup.exe` in your existing Windows installation. This does _not_ work. Try writing the ISO to a USB stick (I personally recommend [Ventoy](https://www.ventoy.net/en/index.html) for this sort of thing; it's awesome), booting your computer from the drive, and installing that way. You should be able to get past the checks that way.

The reason is because the patcher modifies the registry in `boot.wim`, a file on the install ISO, which contains a very light version of Windows called Windows PE, which is used for the installation process when you boot your computer from the installation media. By modifying its registry, we can bypass the TPM, RAM, and CPU checks, as well as a couple others.

Don't worry, you will _not_ have to format your current drive. Instead, on the drive selection screen, you can select the drive that Windows is currently installed to, and Windows will be installed to that drive, preserving your data. In any case, I would still highly recommend backing up your data before **any** upgrade.

-> If you prefer not to boot into the install media, the same registry patches used for the install ISO might be applicable to your current Windows system, which would allow the installer to continue. However, I can't guarantee anything.

Hope this helps! Please don't hesitate to reply with any further issues you run into. I will hold off on closing this issue just in case there is in fact a problem with the patcher.

**Comment by kingyue737** [comment]
Confirmed that `.\Win11-TPM-RegBypass.ps1 -PrepareUpgrade` does work for in-place upgrade. Not require a USB stick. Thanks a lot! Sorry I overlooked that section in the documentation earlier https://github.com/JosephM101/Force-Windows-11-Install#extra-switches
